<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.user.managament</groupId>
        <artifactId>pilates-project</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <artifactId>pilates-app</artifactId>
    <name>pilates-app</name>
    <description>Main application module for the Pilates project.</description>

    <dependencies>
        <!-- Spring Boot Starter -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
        </dependency>

        <!-- Project Modules -->
        <dependency>
            <groupId>com.user.managament</groupId>
            <artifactId>iam-module</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.user.managament</groupId>
            <artifactId>customer-module</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.user.managament</groupId>
            <artifactId>contract-module</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.user.managament</groupId>
            <artifactId>scheduling-module</artifactId>
            <version>${project.version}</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

</project>