<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.user.managament</groupId>
        <artifactId>pilates-project</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <artifactId>shared-module</artifactId>
    <packaging>jar</packaging>
    <name>shared-module</name>
    <description>Shared utilities and classes for the Pilates project.</description>

    <dependencies>
        <!-- SharedUtilClass usa Spring Security, então precisamos desta dependência -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-security</artifactId>
        </dependency>
    </dependencies>

</project>